name: Generate modules list

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-modules-list:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - id: list-modules
        name: List modules
        run: |
          echo "modules=$((cut -d "/" -f1 <<< "$(ls -a */manifest.json)") | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      
      - name: Print mod
        run: echo "$modules"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: "foo"
          event-type: refresh-automation-modules-list
          repository: SekoiaLab/platform
          client-payload: '{"modules": ${{ modules }}}'
